name: Deploy Zola site to Pages

on:
  push:
    branches: [ main ]

# 给 Actions 增加显式的写权限
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true # 必须有这一行，否则你的主题文件夹是空的

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: public
          TOKEN: ${{ secrets.GITHUB_TOKEN }}