name: Deploy Zola site to Pages

on:
  push:
    branches: [ main ]

# --- 新增：强制声明权限，防止因为 GitHub 默认设置导致失败 ---
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true # 必须保留，因为你的主题是子模块

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: public
          TOKEN: ${{ secrets.GITHUB_TOKEN }}